config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about',as:'about'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.ransackable_attributes(auth_object = nil)
    ["body", "created_at", "id", "title", "updated_at", "user_id"]
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum:2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height ]).processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :search_books

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end

  def search_books
    if params[:q].present?
      @q = Book.ransack(params[:q])
      @searched_books = @q.result
    else 
      @q = Book.ransack(params[:q])
      @searched_books = []
    end
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
  book = Book.find(params[:book_id])
  @book_comment = current_user.book_comments.new(book_comment_params)
  @book_comment.book_id = book.id
  if @book_comment.save
    redirect_to book_path(book)
  else
    redirect_to book_path(book)
  end
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!, only: [:index, :new, :show]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = 'You have created book successfully.'
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def index
    # @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div class = 'user_info'>
  <h1>User info</h1>
  <%= image_tag user.get_profile_image(100,100) %>

<table class="table table-striped">
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
</table>

  <% if user == current_user %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-primary" do %>
      <i class = "fas fa-user-cog"></i>
    <% end %>
  <% else %>
    <%= link_to edit_user_path(user),class: "btn btn-outline-primary" do %>
      <i class = "fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

<div class = 'new_book'>
  <h1>New book</h1>
  <%= form_with model: Book.new do |f| %>
  <p>Title</p>
    <%= f.text_field :title %><br>
  <p>Opinion</p>
    <%= f.text_area :body %><br>
    <%= f.submit 'Create Book', class: "btn btn-outline-primary" %>
  <% end %>
</div>

app/views/books/_index.html.erb
<div class = "col-md-8 offset-md-1">
    <h1><%= title || "Books" %></h1>
    <table class="table table-striped">
        <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
        </tr>
            <% books.each do |book| %>
        <tr>
        <td><span><%= link_to(image_tag(book.user.get_profile_image(100, 100)), user_path(book.user)) %></span></td>
        <td><span><%= link_to book.title, book_path(book) %></span></td>
        <td><span><%= book.body %></span></td>
        <td><span>
            <% if book.favorited_by?(current_user) %>
            <%= link_to book_favorites_path(book), method: :delete do %>
                <i class="fas fa-heart" style="color: #001eff;"></i><%= book.favorites.count %>
            <% end %>
            <% else %>
            <%= link_to book_favorites_path(book), method: :post do %>
                <i class="fas fa-heart" style="color: #ff0000;"></i><%= book.favorites.count %>
            <% end %>
            <% end %>
        </span></td>
        <td><span>コメント数:<%= book.book_comments.count %></span></td>
        </tr>
        <% end %>
    </table>
</div>

app/views/books/edit.html.erb
<div class ="container">
  <div class="row justify-content-center">
    <div class="col-md-4">
      <h1>Editing Book</h1>

      <% if @book.errors.any? %>
        <%= @book.errors.count %> <%= @book.errors.count == 1 ? 'error' : 'errors' %>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>


      <%= form_with model: @book do |f| %>
        <label for="inputTitle">Title</label><br>
        <%= f.text_field :title, autofocus: true, id:"inputTitle" %><br>
        <label for="inputOpinion">Opinion</label><br>
        <%= f.text_area :body, autofocus: true, id:"inputOpinion" %>
        <%= f.submit "Update Book", class: "btn btn-outline-primary" %><br>
        <%= link_to 'Show' , book_path(@book) %>
        <%= link_to 'Back' , books_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class ="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'book', user: current_user %>
    </div>

    <% if @searched_books.any? %>
      <%= render 'index', books: @searched_books, title: "Searched Books" %>
    <% else %>
      <%= render 'index', books: @books, title: "Books" %>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<div class ="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'book', user: @book.user %>
    </div>

    <div class = "col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table table-striped">
        <tr>
          <td><span><%= image_tag @book.user.get_profile_image(100,100) %></span><br><%= link_to @book.user.name, user_path(@book.user)%></td>
          <td><span><%= link_to @book.title, book_path(@book) %></span></td>
          <td><span><%= @book.body %></span></td>
            <td><span>
              <% if @book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(@book), method: :delete do %>
                  <i class="fas fa-heart" style="color: #001eff;"></i><%= @book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(@book), method: :post do %>
                  <i class="fas fa-heart" style="color: #ff0000;"></i><%= @book.favorites.count %>
                <% end %>
              <% end %>
            </span></td>
            <td><span>コメント数:<%= @book.book_comments.count %></span></td>
          <% if @book.user == current_user %>
            <td><span><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-outline-primary" %></span></td>
            <td><span><%= link_to 'Destroy', book_path(@book), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-outline-danger"  %></span></td>
          <% end %>
        </tr>
      </table>
        <% if @book_comment.errors.any? %>
          <div class="alert alert-danger">
            <ul>
              <% @book_comment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      <table>
        <tr>
          <th></th>
          <th></th>
          <th></th>
        </tr>
          <% @book.book_comments.each do |book_comment| %>
            <tr>
              <td><%= image_tag book_comment.user.get_profile_image(70,70) %><br><%= book_comment.user.name %></td>
              <td><%= book_comment.comment %></td>
              <td>
                <% if book_comment.user == current_user %>
                  <%= link_to "Destroy", book_book_comment_path(book_comment.book,book_comment), method: :delete %>
                <% end %>
              </td>
            </tr>
          <% end %>
      </table>

      <%= form_with model:[@book, @book_comment] do |f| %>
        <%= f.text_area :comment %><br>
        <%= f.submit "送信" %>
      <% end %>

    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class = "container">
  <div class = "row">
    <h1 class = "mx-auto">Welcome to <i class="fas fa-book"></i>Bookers!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class ="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1>Welcome to <i class="fas fa-book"></i> Bookers!!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p><br>
      <p>you can share and exchange your opinions , inpressions , and emotions<br>
      about various books!</p>

      <div class="d-flex justify-content-center">
        <%= link_to "Log in", new_user_session_path, class: "btn btn-outline-primary mr-3" %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <a class="navbar-brand text-light" href="/">Bookers</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">

    <% if user_signed_in? %>
      <li class="nav-item text-light d-flex align-items-center">
        <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
          <i class="fas fa-home"></i>Home
        <% end%>
      </li>
      <li class="nav-item text-light d-flex align-items-center">
        <%= link_to users_path, class: 'nav-link text-light' do  %>
          <i class="fas fa-users"></i>Users
        <% end %>
      </li>
      <li class="nav-item text-light d-flex align-items-center">
        <%= link_to books_path, class: 'nav-link text-light' do %>
          <i class="fas fa-book-open"></i> Books
        <% end %>
      </li>
      <li class="nav-item text-light d-flex align-items-center">
        <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
          <i class="fas fa-sign-out-alt"></i>Log out
        <% end %>
      </li>
    <% else %>
      <li class="nav-item d-flex align-items-center">
        <%= link_to root_path, class: 'nav-link text-light' do %>
          <i class="fas fa-home"></i> Home
        <% end %>
      </li>
      <li class="nav-item d-flex align-items-center">
        <%= link_to about_path, class: 'nav-link text-light' do%>
          <i class="fas fa-link"></i>About
        <% end %>
      </li>
      <li class="nav-item d-flex align-items-center">
        <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
          <i class="fas fa-user-plus"></i>Sign up
        <% end %>
      </li>
      <li class="nav-item d-flex align-items-center">
        <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
          <i class="fas fa-sign-in-alt"></i>Log in
        <% end %>
      </li>
    <% end %>
      </ul>
    </div>
    </nav>
    <%= search_form_for @q, url: books_path do |f| %>
      <%= f.search_field :title_cont %>
      <%= f.submit "検索" %>
    <% end %>
    </header>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: key) %>
    <% end %>

    <%= yield %>

  <footer>
    <div class ="container mt-5">
      <div class = "row">
        <div class= "mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>

  </body>

</html>

app/views/users/edit.html.erb
<div class ="container">
  <div class="row justify-content-center">
    <div class="col-md-4">
      <h1>User info</h1>

      <% if @user.errors.any? %>
        <%= @user.errors.count %>件のエラーが発生しました
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model: @user do |f| %>
        <label for="inputName">Name</label><br>
        <%= f.text_field :name, autofocus: true, id:"inputName" %><br>
        <label for="inputImage">Image</label>
        <%= f.file_field :profile_image, placeholder: "ファイルを選択", accept: "image/*" %>
        <label for="inputIntroduction">Introduction</label><br>
        <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction" %>
        <%= f.submit "Update User", class: "btn btn-outline-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class ="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/book', user: current_user, book: @book %>
    </div>

    <div class = "col-md-8 offset-md-1">
      <h1>Users</h1>
        <table class="table table-striped">
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
            <% @users.each do |user| %>
            <tr>
              <td><span><%= image_tag user.get_profile_image(100,100) %></span></td>
              <td><span><%= user.name %></span></td>
              <td><span><%= link_to 'Show', user_path(user) %></span></span></td>
            </tr>
            <% end %>
        </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class ="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/book', user: @user, book: @book %>
    </div>

    <div class = "col-md-8 offset-md-1">
      <h1>Books</h1>

      <table class="table table-striped">
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
          </tr>
            <% @books.each do |book| %>
            <tr>
              <td><span><%= link_to image_tag book.user.get_profile_image(100,100) %></span></td>
              <td><span><%= link_to book.title, book_path(book)%></span></td>
              <td><span><%= book.body %></span></span></td>
              <td><span>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    <i class="fas fa-heart" style="color: #001eff;"></i><%= book.favorites.count %>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <i class="fas fa-heart" style="color: #ff0000;"></i><%= book.favorites.count %>
                  <% end %>
                <% end %>
              </span></td>
              <td><span>コメント数:<%= book.book_comments.count %></span></td>
            </tr>
            <% end %>
      </table>
    </div>
  </div>
</div>